# artifactDescription: "DIH Domain"
annotationLibrary: "none"
dateLibrary: "java8"
# groupId: "dk.rdpl.dih"
# modelPackage: "dk.rdpl.dih.domain.model"
# artifactId: "domain"
performBeanValidation: "true"
useBeanValidation: "true"
scmConnection: ""
scmDeveloperConnection: ""
scmUrl: ""
