name: "Load Environment Variables"
description: "Loads the .env file"
inputs:
  azureDeployRepoToken:
    description: "The token of the azure-deploy repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout common-deploy
      uses: actions/checkout@v4
      with:
        repository: Redpill-Linpro-DK/dih-fair-common
        ref: main
        token: ${{ inputs.azureDeployRepoToken }}
        path: tmp-repo

    - name: Load environment variables
      uses: ./tmp-repo/.github/actions/loadEnvVariables
      with:
        rootDir: tmp-repo
